yatube/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'yatube'
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('group/', include('posts.urls', namespace='group_posts')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        max_length=200,
        help_text='200 символов max',
        verbose_name='Текст',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        help_text='дата',
        verbose_name='Дата',
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        help_text='автор',
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.CASCADE,
        blank=True, null=True,
        help_text='группа',
        verbose_name='Группа',
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        default_related_name = 'posts'
        verbose_name = 'posts'
        verbose_name_plural = 'посты'

    def __str__(self) -> str:
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        help_text='200 символов max',
        verbose_name='Название',
    )
    slug = models.SlugField(
        unique=True,
        max_length=200,
        help_text='текст',
        verbose_name='Пояснения',
    )
    description = models.TextField(
        help_text='Опишите группу',
        verbose_name='Описание',
    )

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower',
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=('author', 'user'), name='unique_names'),
        ]

    def __str__(self) -> str:
        return f'{self.user} подписан на {self.author}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from .models import User, Post, Group, Follow
from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGINATOR_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, settings.PAGINATOR_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, settings.PAGINATOR_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_amount = posts.count()
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=user).exists()
    else:
        following = None
    context = {
        'posts': posts,
        'page_obj': page_obj,
        'author': user,
        'post_amount': post_amount,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    posts_count = post.author.posts.all().count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'posts': post,
        'posts_count': posts_count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


def post_create(request):
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(request.POST or None,
                        files=request.FILES or None)
        if form.is_valid():
            post_create = form.save(commit=False)
            post_create.author = request.user
            post_create.save()
            return redirect('posts:profile', username=request.user.username)
    else:
        form = PostForm()
    return render(request, template, {'form': form, 'is_edit': False})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    post_page = Post.objects.filter(author__following__user=user)
    paginator = Paginator(post_page, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'post_page': post_page,
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    if username != request.user.username:
        author_follow = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(user=request.user, author=author_follow)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    followed_author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=followed_author)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %} 
{% load static %}  
{% load thumbnail %} 
{%block content%} 
 
    <main> 
      <div class="container py-5"> 
        <div class="row justify-content-center"> 
          <div class="col-md-8 p-5"> 
            <div class="card"> 
              <div class="card-header">   
               Новый пост          
              </div> 
                <div class="card-body">         
                  <form method="post" enctype="multipart/form-data"> 
                  {% csrf_token %} 
                                 {% if form.errors %} 
                  {% for field in form %} 
                    {% for error in field.errors %}             
                      <div class="alert alert-danger"> 
                        {{ error|escape }} 
                      </div> 
                    {% endfor %} 
                  {% endfor %} 
                {% for error in form.non_field_errors %} 
                  <div class="alert alert-danger"> 
                    {{ error|escape }} 
                  </div> 
                {% endfor %} 
                  {% endif %}         
                <div class="form-group row my-3 p-3"> 
                    <label for="id_text"> 
                      Текст поста                   
                      <span class="required text-danger" >*</span>                   
                    </label> 
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text"> 
                    </textarea> 
                    <small id="id_text-help" class="form-text text-muted"> 
                      Текст нового поста  
                    </small>                 
                  </div>        
                  <div class="form-group row my-3 p-3"> 
                    <label for="id_group">Группы</label> 
                      {{ form.group }} 
                    <small id="id_group-help" class="form-text text-muted"> 
                    Группа, к которой будет относиться пост 
                    </small> 
                  </div> 
                   <div class="form-group row my-3 p-3"> 
                    <label for="id_image"> 
                      Картинка                       
                    </label> 
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                       
                  </div>  
                    <div class="d-flex justify-content-end"> 
                      <button type="submit" class="btn btn-primary"> 

                        {% if is_edit %} 
                         Оставить для потомков  
                        {% else %} 
                          Добавить  
                        {% endif %}    
                      </button>  
                  </div> 
                </form> 
              </div> 
            </div> 
          </div> 
        </div> 
      </div> 
    </main> 
{%endblock %} 

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}
    <h1>Мои подписки:</h1>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% for post in page_obj %}
            <ul>
                <li>
                    <a href="{% url 'posts:profile' post.author.username %}"> Автор: {{ post.author }}</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            <p>{% thumbnail post.image "380x220" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}</p>
            {% cache 20 index_page request.user.username %}
                {% if post.group %}
                    <a href="{% url 'posts:group_posts' post.group.slug %}"> Все записи
                        группы: {{ post.group.title }}</a>
                {% endif %}
            {% endcache %}
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    {% endif %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
    <h1>{{ group.title }}</h1>
{% endblock %}
{% block header %}
    {{ group.title }}
{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1> Записи сообщества: {{ group.title }} </h1>
        <p>{{ group.description }}</p>
        <article>
            {% for post in posts %}
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                        <a href="{% url 'posts:profile' post.author.username %}"> Все посты пользователя</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d M Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text|truncatewords:30 }}
                </p>
                {% thumbnail post.image "380x220" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <a href="{% url 'posts:post_detail' post.pk %}"> Подробная информация </a>
                </article>
                {% if post.group %}
                    <a href="{% url 'posts:group_posts' post.group.slug %}"> Все записи группы</a>
                {% endif %}
                {% if not forloop.last %}
                    <hr>{% endif %}
            {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
    <h1>Последние обновления на сайте </h1>
{% endblock %}
{% block content %}
    {% load cache %}
    {% cache 20 index_page %}
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
            <ul>
                <li>
                    <a href="{% url 'posts:profile' post.author.username %}"> Автор: {{ post.author }}</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                <li>
                    {% if post.group %}
                        <a href="{% url 'posts:group_posts' post.group.slug %}"> Все записи группы: {{ post.group.title }}</a>
                    {% endif %}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "380x220" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} <h2>{{ posts.text|truncatewords:15 }}</h2> {% endblock %}
{% block content %}
    {% load user_filters %}
    {% load thumbnail %}
    <body>
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ posts.pub_date|date:"d E Y" }}

                <li class="list-group-item">
                    Автор: {{ posts.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span> {{ posts_count }} </span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Группа: {{ posts.group.title }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <p>{% thumbnail posts.image "380x220" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}</p>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            <p>
                {{ post.text }}
            </p>
        </article>
    </div>
    {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' posts.id %}">
                    {% csrf_token %}
                    <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
    {% endif %}
    {% for comment in comments %}
        <div class="media mb-4">
            <div class="media-body">
                <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                    </a>
                </h5>
                <p>
                    {{ comment.text }}
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}    

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} <h1> Аффтар {{ author }} </h1> {% endblock %}
{% block content %}
    {% load thumbnail %}
    <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_count }}</h3>
        {% if following %}
            <a
                    class="btn btn-lg btn-light"
                    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
                Отписаться
            </a>
        {% else %}
            <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
                Подписаться
            </a>
        {% endif %}
    </div>
    <h1>Все посты пользователя {{ author.get_full_name }}  </h1>
    <h3>Всего постов: {{ post_amount }} </h3>
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    <a href="{% url 'posts:profile' post.author.username %}"> Все посты
                        пользователя: {{ post.author }}</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                <li>
                    <a href="{% url 'posts:post_detail' post.id %}"> Подробная информация </a>
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "380x220" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
        </article>
        {% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}"> Все записи группы: {{ post.group.title }}</a>
        {% endif %}
        {% if not forloop.last %}
            <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %} 